# Generated by Django 5.2.1 on 2025-05-31 17:53

import blog_app.models
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Versión amigable para URL del título (se genera automáticamente si se deja vacío).', max_length=220, unique=True)),
                ('summary', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Un breve resumen que aparecerá en la lista de posts.', null=True, verbose_name='Resumen Corto / Introducción')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido Principal')),
                ('featured_image', models.ImageField(blank=True, help_text='Imagen principal que se mostrará para el post.', null=True, upload_to=blog_app.models.post_image_path, verbose_name='Imagen Destacada')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Puede ser una fecha futura para programar la publicación.', verbose_name='Fecha de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='Estado')),
                ('meta_description', models.CharField(blank=True, help_text='Descripción breve para motores de búsqueda (máx. 160 caracteres).', max_length=160, null=True, verbose_name='Meta Descripción (SEO)')),
                ('keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas.', max_length=255, null=True, verbose_name='Palabras Clave (SEO)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Post / Página',
                'verbose_name_plural': 'Posts / Páginas',
                'ordering': ['-published_date'],
            },
        ),
    ]
